plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "org.dmsg.client"
    compileSdk = 37
    // Only 37.0.0 is installed in this environment.
    buildToolsVersion = "37.0.0"

    defaultConfig {
        applicationId = "org.dmsg.client"
        minSdk = 26
        targetSdk = 37
        versionCode = 1
        versionName = "0.4.0-k4"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        ndk { abiFilters += "arm64-v8a" }
        // Budgets (ARCH/WORK_PLAN M4): release APK <= 25 MiB, idle PSS <= 100 MiB.
        // Measured on device in the gate checklist; not promised here.
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        getByName("debug") {
            isMinifyEnabled = false
            // Destructive clear-data gate uses an isolated applicationId, never the live account.
            if (providers.gradleProperty("gateInstall").orNull == "true") applicationIdSuffix = ".gate"
        }
        getByName("release") {
            // Local runtime profiling only; default release remains unsigned for real signing.
            if (providers.gradleProperty("gateInstall").orNull == "true") applicationIdSuffix = ".gate"
            if (providers.gradleProperty("gateReleaseSigned").orNull == "true") {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    packaging {
        // Native libdmsg_core.so is built with cargo-ndk when an NDK is present
        // (see docs gate checklist). Debug APK without it still assembles; the
        // app reports "core missing" instead of crashing (see Core.kt).
        // Legacy packaging extracts .so at install: UniFFI uses JNA, which needs
        // a real file. API/page-size runtime evidence lives in the checklist.
        jniLibs {
            useLegacyPackaging = true
        }
    }
    // Generated by build-native.sh, not committed binaries in src/main.
    sourceSets.getByName("main").jniLibs.setSrcDirs(listOf("build/nativeLibs"))
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("androidx.activity:activity-ktx:1.11.0")
    implementation("androidx.core:core-ktx:1.16.0")
    // UniFFI runtime for generated bindings (uniffi/dmsg_core/dmsg_core.kt).
    // The jar's Linux dispatch is not Android/bionic; use the Android AAR.
    implementation("net.java.dev.jna:jna:5.18.1@aar")
    // QR: show contact-QR + offline scan (both dmsg:// formats).
    implementation("com.google.zxing:core:3.5.4")
    implementation("androidx.camera:camera-core:1.4.2")
    implementation("androidx.camera:camera-camera2:1.4.2")
    implementation("androidx.camera:camera-lifecycle:1.4.2")
    implementation("androidx.camera:camera-view:1.4.2")
    // Keystore-wrap master key + EncryptedFile sealing (see SecureStore.kt).
    implementation("androidx.security:security-crypto:1.0.0")
    // Tink classes referenced by security-crypto require these annotations at R8 time.
    implementation("com.google.errorprone:error_prone_annotations:2.28.0")
    implementation("com.google.code.findbugs:jsr305:3.0.2")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test:core-ktx:1.6.1")
}

// AGP's connected test task uninstalls its target afterward, removing the
// Android Keystore identity. Never run it against the live applicationId.
gradle.taskGraph.whenReady {
    // Reject before any dependency task can install or manipulate the live target.
    if (allTasks.any { it.project == project && it.name.startsWith("connected") && it.name.endsWith("AndroidTest") }) {
        check(providers.gradleProperty("gateInstall").orNull == "true") {
            "Use -PgateInstall=true: connected tests uninstall their target package"
        }
    }
}
