import java.io.File
import java.util.Base64

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

/** Optional public deployment input, never a tracked domain/pin or an invitation. */
abstract class GenerateTrustedServerProfile : DefaultTask() {
    @get:InputFile
    @get:Optional
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val profile: RegularFileProperty
    @get:OutputDirectory
    abstract val assets: DirectoryProperty

    @TaskAction
    fun generate() {
        val output = assets.get().asFile
        output.deleteRecursively() // Omission must not accidentally package an older deployment.
        check(output.mkdirs()) { "Unable to create generated public assets" }
        if (!profile.isPresent) return
        val bytes = profile.get().asFile.inputStream().use { it.readNBytes(8193) }
        check(bytes.size <= 8192 && bytes.all { it.toInt() in 0..127 }) { "Invalid bounded public server profile" }
        val code = bytes.toString(Charsets.US_ASCII).filterNot { it == ' ' || it == '\t' || it == '\r' || it == '\n' }
        val prefix = "dmsg://server/"
        check(code.startsWith(prefix) && code.length <= 13 + (4096 * 4 + 2) / 3) { "Expected a bounded public server profile" }
        val payload = code.removePrefix(prefix)
        check(payload.isNotEmpty() && payload.all { it in 'A'..'Z' || it in 'a'..'z' || it in '0'..'9' || it == '-' || it == '_' }) {
            "Expected canonical public server profile encoding"
        }
        val decoded = try { Base64.getUrlDecoder().decode(payload) }
            catch (_: IllegalArgumentException) { throw GradleException("Invalid public server profile encoding") }
        check(decoded.size <= 4096 && Base64.getUrlEncoder().withoutPadding().encodeToString(decoded) == payload) {
            "Expected canonical bounded public server profile encoding"
        }
        output.resolve("server-profile.txt").writeText(code, Charsets.US_ASCII)
    }
}

val generateTrustedServerProfile = tasks.register<GenerateTrustedServerProfile>("generateTrustedServerProfile") {
    profile.set(layout.file(providers.gradleProperty("serverProfileFile").map { path ->
        val input = File(path)
        check(input.isAbsolute) { "serverProfileFile must be an absolute public-profile file path" }
        input
    }))
    assets.set(layout.buildDirectory.dir("generated/trustedServerProfile/assets"))
}

android {
    namespace = "org.dmsg.client"
    compileSdk = 37
    // Only 37.0.0 is installed in this environment.
    buildToolsVersion = "37.0.0"

    defaultConfig {
        // Dependency translations must not select an unsupported app language ahead of RU/EN.
        resourceConfigurations += listOf("en", "ru")
        applicationId = "org.dmsg.client"
        minSdk = 26
        targetSdk = 37
        versionCode = 2
        versionName = "0.4.1-53"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        ndk { abiFilters += "arm64-v8a" }
        // Budgets (ARCH/WORK_PLAN M4): release APK <= 25 MiB, idle PSS <= 100 MiB.
        // Measured on device in the gate checklist; not promised here.
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        getByName("debug") {
            isMinifyEnabled = false
            // Destructive clear-data gate uses an isolated applicationId, never the live account.
            if (providers.gradleProperty("gateInstall").orNull == "true") applicationIdSuffix = ".gate"
        }
        getByName("release") {
            // Local runtime profiling only; default release remains unsigned for real signing.
            if (providers.gradleProperty("gateInstall").orNull == "true") applicationIdSuffix = ".gate"
            if (providers.gradleProperty("gateReleaseSigned").orNull == "true") {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    packaging {
        // Native libdmsg_core.so is built with cargo-ndk when an NDK is present
        // (see docs gate checklist). Debug APK without it still assembles; the
        // app reports "core missing" instead of crashing (see Core.kt).
        // Legacy packaging extracts .so at install: UniFFI uses JNA, which needs
        // a real file. API/page-size runtime evidence lives in the checklist.
        jniLibs {
            useLegacyPackaging = true
        }
    }
    // Generated by build-native.sh, not committed binaries in src/main.
    sourceSets.getByName("main").jniLibs.setSrcDirs(listOf("build/nativeLibs"))
    sourceSets.getByName("main").assets.srcDir(generateTrustedServerProfile.flatMap { it.assets })
}

tasks.named("preBuild") { dependsOn(generateTrustedServerProfile) }

// One file, not a Copy output-directory encompassing the entire repository.
abstract class Export53Apk : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val apk: RegularFileProperty
    @get:OutputFile
    abstract val destination: RegularFileProperty
    @get:Input
    abstract val gateInstall: Property<Boolean>

    @TaskAction
    fun export() {
        check(!gateInstall.get()) {
            "53.apk is the main package; export without -PgateInstall=true"
        }
        apk.get().asFile.copyTo(destination.get().asFile, overwrite = true)
    }
}

// Installable development artifact, without changing the package/signing identity.
tasks.register<Export53Apk>("export53Apk") {
    dependsOn("assembleDebug")
    apk.set(layout.buildDirectory.file("outputs/apk/debug/app-debug.apk"))
    destination.set(rootProject.layout.projectDirectory.file("../53.apk"))
    gateInstall.set(providers.gradleProperty("gateInstall").map { it == "true" }.orElse(false))
}

dependencies {
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("androidx.activity:activity-ktx:1.11.0")
    implementation("androidx.core:core-ktx:1.16.0")
    // Native message spans only; keep Markwon's default CommonMark dependency.
    implementation("io.noties.markwon:core:4.6.2")
    implementation("io.noties.markwon:ext-strikethrough:4.6.2")
    // UniFFI runtime for generated bindings (uniffi/dmsg_core/dmsg_core.kt).
    // The jar's Linux dispatch is not Android/bionic; use the Android AAR.
    implementation("net.java.dev.jna:jna:5.18.1@aar")
    // QR: show contact-QR + offline scan (both dmsg:// formats).
    implementation("com.google.zxing:core:3.5.4")
    implementation("androidx.camera:camera-core:1.4.2")
    implementation("androidx.camera:camera-camera2:1.4.2")
    implementation("androidx.camera:camera-lifecycle:1.4.2")
    implementation("androidx.camera:camera-view:1.4.2")
    // Keystore-wrap master key + EncryptedFile sealing (see SecureStore.kt).
    implementation("androidx.security:security-crypto:1.0.0")
    // Tink classes referenced by security-crypto require these annotations at R8 time.
    implementation("com.google.errorprone:error_prone_annotations:2.28.0")
    implementation("com.google.code.findbugs:jsr305:3.0.2")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test:core-ktx:1.6.1")
}

// AGP's connected test task uninstalls its target afterward, removing the
// Android Keystore identity. Never run it against the live applicationId.
gradle.taskGraph.whenReady {
    // Reject before any dependency task can install or manipulate the live target.
    if (allTasks.any { it.project == project && it.name.startsWith("connected") && it.name.endsWith("AndroidTest") }) {
        check(providers.gradleProperty("gateInstall").orNull == "true") {
            "Use -PgateInstall=true: connected tests uninstall their target package"
        }
    }
}
